### ISSUE TITLE
Simplify native library loading

### ISSUE THREAD

**Issue by sigiesec** [zeromq/clrzmq4#109]
The code for loading native libraries (libzmq, libsodium) is complex, and the behaviour it implements is proprietary. This could be simplified, and the directory layout for complex use cases where multiple architectures must be supported in a single deployment can be left to the application. In particular if an application directly or indirectly uses other native libraries, this may simplify the deployment of that application.

In particular, the following hints should be observed resp. recommended to application developers:
* http://www.mono-project.com/docs/advanced/pinvoke/
* https://stackoverflow.com/a/156024/2019765

Are there any other opinions on this?

**Comment by metadings** [comment]
Well, I actually do have a static method `lib.Platform.SetupImplementation()`, which is to be used in the static constructor (of a class); a method which is loading binary assemblies from PATH on Windows and LD_LIBRARY_PATH on Posix, and using `{PlaceHolders}`. Using `DllImport`, you can specify where to load binary assemblies by their name, for example "zmq" or "sodium" or "sqlite3".

The method `lib.Platform.SetupImplementation()` does also setup `public readonly` delegates: for example you use `Platform.LoadUnmanagedLibrary`, the method decides whether you do actually use `Platform.Posix.LoadUnmanagedLibrary` or `Platform.Win32.LoadUnmanagedLibrary`.

Works on Windows (`*.dll`) and also on Linux (`lib*.so`) and should also work on MacOSX.
On Android method to function pointers are `__Internal`.

**Comment by metadings** [comment]
I'm sorry, I have no idea for [PR138 Replace Mono's __Internal with libdl on Posix](https://github.com/zeromq/clrzmq4/pull/138), also for .NET Core support.

I loved the idea to have a folder `i386` and a folder `amd64` for unmanaged C libraries.
1. I loved the idea, because I was on a Windows x86 AND a Windows amd64 system,
and I didn't want to recompile libzmq always, because first I do need msbuild or the like which is not present on a Windows system in the first place - where on every Linux system also gcc is installed. 
2. The Windows binaries on zeromq.org are SOMEWHAT OUTDATED, staying at v4.0.4 from 2014? and I didn't like this.

However, I do now believe we should remove this whole Platform issue, staying with what .NET Framework, mono and .NET Core gives you on the hand for P/Invoke.
Perhaps we can let these binaries in a git folder.
Is that okay for you?

**Comment by sigiesec** [comment]
Regarding your second point, I think prebuilt Windows binaries are now available via nu-get, but the ZeroMQ website does not mention this.

In general I think removing the custom library loading strategies in Platform is a good idea. It needs some migration effort for users, but it makes it easier to support all .NET/Mono flavours, and makes things more straightforward for users, in particular when their applications use multiple native libraries.

**Comment by metadings** [comment]
Closing this issue. It's too old
