### ISSUE TITLE
Always Open Issue: New NuGet Package

### ISSUE THREAD

**Issue by metadings** [zeromq/clrzmq4#122]
I've made a new [nuGet Package ZeroMQ v4.1.023](https://www.nuget.org/packages/ZeroMQ/4.1.0.23) D2017-09-06 ([download](https://www.nuget.org/api/v2/package/ZeroMQ/4.1.0.23))

**Comment by sigiesec** [comment]
Some remarks:
* I think it would have been better to increase the minor version number.
* It is not a good idea to release a version that does not even build correctly: https://ci.appveyor.com/project/zeromq/clrzmq4/build/4.2.0.130
* The tag names should contain the version number rather than the date. The date is redundant, 
* Why have the old releases disappeared from github?
* The .zip file attached to https://github.com/zeromq/clrzmq4/releases/tag/2017-09-06 does not correspond to that tag. At least the version inside the AssemblyInfo.cs has been modified outside the repository.

**Comment by metadings** [comment]
* I think it would have been better to increase the minor version number.

ZeroMQ/clrzmq4 is based on ZeroMQ/zeromq4-1, just to be sure they are ready-to-go binaries in there...


* Why have the old releases disappeared from github?

Because I don't want You to download a 2 1/2 years old binary.

* The tag names should contain the version number rather than the date. The date is redundant,
* The .zip file attached to https://github.com/zeromq/clrzmq4/releases/tag/2017-09-06 does not correspond to that tag. At least the version inside the AssemblyInfo.cs has been modified outside the repository.

OHa ... well I'm not really good in nuget their project.json, project.config, ZeroMQ.nuspec, .csproj and then the versioning in .net core, .net standard, .net... That my git directory isn't up-to-date, that is sh:recycle:t.

**Comment by DarkMinded** [comment]
Please correct the project , i'm can not debug my project right now because i updated ZeroMQ, right now you have non functioning framework this is very serious ! 

I'm geting this error the files are no were to be found

Severity	Code	Description	Project	File	Line	Suppression State
Error		Could not copy the file "C:\Users\nanjo\Documents\Visual Studio 2017\Projects\clrzmq4-master\i386\libsodium.so" because it was not found.	ZeroMQ.VS			
Error		Could not copy the file "C:\Users\nanjo\Documents\Visual Studio 2017\Projects\clrzmq4-master\amd64\libsodium.so" because it was not found.	ZeroMQ.VS

**Comment by sigiesec** [comment]
@DarkMinded the build should be fixed by #124

**Comment by joaogarrett** [comment]
I also have the same problem as @DarkMinded. IMO, you should have kept at least the last version (4.1.22) still available for download.

**Comment by sigiesec** [comment]
I think it is not a good idea to remove any published release. Maybe if it were unusable, but not in a normal case.

**Comment by sigiesec** [comment]
I think you can still download the old source code from https://github.com/zeromq/clrzmq4/releases/tag/2016-12-14 
As said above, it is somewhat confusing that the tag does not contain the version number.

**Comment by metadings** [comment]
I've made a new [nuGet Package ZeroMQ v4.1.0.25](https://www.nuget.org/packages/ZeroMQ/4.1.0.25) D2017-09-09 ([download](https://www.nuget.org/api/v2/package/ZeroMQ/4.1.0.25))

**Comment by DarkMinded** [comment]
Thank You, Will check it this week and get back to you



Best Regards


Nuno Anjos


________________________________
De: Uli Riehm <notifications@github.com>
Enviado: 11 de setembro de 2017 13:48
Para: zeromq/clrzmq4
Cc: DarkMinded; Mention
Assunto: Re: [zeromq/clrzmq4] Always Open Issue: New NuGet Package (#122)


I've made a new nuGet Package ZeroMQ v4.1.025<https://www.nuget.org/packages/ZeroMQ/4.1.0.25> D2017-09-09 (download<https://www.nuget.org/api/v2/package/ZeroMQ/4.1.0.25>)

**Comment by metadings** [comment]
I've made a new [nuGet Package ZeroMQ v4.1.0.26](https://www.nuget.org/packages/ZeroMQ/4.1.0.26) D2017-09-22 ([download](https://www.nuget.org/api/v2/package/ZeroMQ/4.1.0.26)). 

Now we have a Windows libzmq.dll, Linux libzmq.so, featuring a new MacOSX libzmq.dylib, thanks to @sigiesec !

**Comment by DarkMinded** [comment]
Thanks,  im using it, it is working 100%

Em 30/09/2017 10:23, Uli Riehm <notifications@github.com> escreveu:

I've made a new nuGet Package ZeroMQ v4.1.0.26<https://www.nuget.org/packages/ZeroMQ/4.1.0.26> D2017-09-22 (download<https://www.nuget.org/api/v2/package/ZeroMQ/4.1.0.26>). Now we have a Windows libzmq.dll, Linux libzmq.so, featuring a new MacOSX libzmq.dylib, thanks to @sigiesec<https://github.com/sigiesec> !

**Comment by M1ghty1** [comment]
Hello, we use the latest Nuget Package 4.1.0.26. But our OWASP Dependency Check marks this as a vulnerability because it detects it as libzmq version less than 4.1.1 ( though the actually used version is 4.2.2).
This is because the version number of this nuget package is not "synchronous" to the used libzmq although the nuget package is simply called ZeroMQ (and not clrzmq).
Would it be reasonable to adjust the version to the actually used libzmq version (or rename the nuget package)?

Also a current nuget package with the latest libzmq 4.2.5 would be great :-)

Best regards,
Martin

**Comment by DarkMinded** [comment]
If this is pool I have no problems with th renaming or re-numbering of the version, less incompatiblilies is always better for the future!

Em 23/10/2018 07:58, M1ghty1 <notifications@github.com> escreveu:

Hello, we use the latest Nuget Package 4.1.0.26. But our OWASP Dependency Check marks this as a vulnerability because it detects it as libzmq version less than 4.1.1 ( though the actually used version is 4.2.2).
This is because the version number of this nuget package is not "synchronous" to the used libzmq although the nuget package is simply called ZeroMQ (and not clrzmq).
Would it be reasonable to adjust the version to the actually used libzmq version (or rename the nuget package)?

Also a current nuget package with the latest libzmq 4.2.5 would be great :-)

Best regards,
Martin

**Comment by metadings** [comment]
Closing this issue. It's too old - Use [nuget v4.1.0.30](https://www.nuget.org/packages/ZeroMQ/4.1.0.30) instead.

**Comment by M1ghty1** [comment]
I'm sorry but now I'm confused about which version of libzmq is actually used.
The readme says 
> for Windows (libzmq 4.1.n) 

Wouldn't this be a step backwards because in previous versions libzmq 4.2.2 was used?

On the other hand appveyor.yml creates a link to a libzmq-mt-4_3_1.dll
:confused:
