### ISSUE TITLE
Specify supported compiler versions and used C# language version

### ISSUE THREAD

**Issue by sigiesec** [zeromq/clrzmq4#125]
It is unclear which compiler versions are supported, and which C# language version may be used in the clrzmq4 source code. The README.md file only refers to the supported execution environments for the binaries. This should be amended by information on compiler versions and/or C# language version.

**Comment by metadings** [comment]
1. **Hello. I've made a new ZeroMQ namespace for .NET Framework 4+ and mono 5+.**

2. I don't want this project, not to compile in a machine using somehow a framework v4.0.
There are hundreds lines of code, and I DON'T want this NOT to run, just because of operator `?.`, which would be just in `class ZThread`, an awesome class you just do want to override, so please let this operator just out of this class.

**Comment by sigiesec** [comment]
.NET Framework 4+ is not a compiler.

I am not arguing that the language version should be changed, I am fine with using a pre-C# 6.0 version, but I would like that to be specified.

**Comment by sigiesec** [comment]
http://www.mono-project.com/docs/about-mono/languages/csharp/ says:

> The Mono C# compiler is considered feature complete for C# 1.0, C# 2.0, C# 3.0, C# 4.0, C# 5.0 and C# 6.0 (ECMA).

**Comment by sigiesec** [comment]
Based on this, I don't really understand why C# 6.0 should not be used, but this can be discussed somewhere else.
