### ISSUE TITLE
Important Update: ReceiveBytes returns now int, ReadString doesn't enc.GetMaxByteCount

### ISSUE THREAD

**Issue by metadings** [zeromq/clrzmq4#22]
[ZSocket.ReceiveBytes](https://github.com/zeromq/clrzmq4/blob/master/ZSocket.cs#L305) method now does return `int`, and `-1` if there was a [`ZError`](https://github.com/zeromq/clrzmq4/blob/master/ZError.cs#L11).
Do not use [`zmq_recv`](http://api.zeromq.org/4-1:zmq-recv) in favor of [`zmq_msg_recv`](http://api.zeromq.org/4-1:zmq-msg-recv)!
Please have a look on [`ZSocket.ReceiveFrame`](https://github.com/zeromq/clrzmq4/blob/master/ZSocket.cs#L493) and [`ZSocket.ReceiveMessage`](https://github.com/zeromq/clrzmq4/blob/master/ZSocket.cs#L409),
where you receive and send `ZFrame msg` and `ZMessage msg` (basically an `IList<ZFrame>`).

[ZFrame.ReadString](https://github.com/zeromq/clrzmq4/blob/master/ZFrame.cs#L529) method now doesn't try `= encoding.GetMaxByteCount(length)`.

[ZFrame.ReadLine](https://github.com/zeromq/clrzmq4/blob/master/ZFrame.cs#L549) is a new method,
which returns a string ending in LineFeed `\n` `0x0A` possibly followed by a CarriageReturn `\r` `0x0D`.

**Comment by metadings** [comment]
There needs to be someone, who takes some `byte[]` reading the `\n` with encoding into a string `char[]`.

**Comment by zanfranceschi** [comment]
I'm not sure if it fits here -- i'm sorry if not. ZFrame.ReadString() is not reading all the received string in one call. I'm having to ZFrame.ReadString() more than once in a loop to read all the received string.

I'm doing something like:

```
string theStringIWant = string.Empty;
string auxString = string.Empty;

do
{
    auxString = frame.ReadString();
    theStringIWant += auxString;
}
while (!string.IsNullOrEmpty(auxString));
```

I've tried different Encoding and nothing changed. Anyway, I found out that for each special character used in the string, there is one less byte in the string after calling ReadString(). For instance:

If my sent string is:
Hêllo

The following happens in the receiving side:

```
a = frame.ReadString();
b = frame.ReadString();
// a = Hêll
// b = o
```

That's way I'm using a loop.

Is this by design or is it a bug?

I'm using the nuget version 4.1.0.15

**Comment by metadings** [comment]
You definitifely need the update to the current version (v4.1.0.17)... I don't know if I got it right in the last version (v...15, v...16) so please just install/`git pull` the update.

That was a bug resolved in some commit with ReadString and ReadLine...

**Comment by zanfranceschi** [comment]
This bug persists in the 4.1.0.17 version. Just tried it.

**Comment by metadings** [comment]
I don't have problems right now... Please try writing/reading the string using Encoding.ASCII.

**Comment by metadings** [comment]
irrelevant, as of v4.1.0.xx
