### ISSUE TITLE
Push Memory Leak using frames, probably apply to other schemes also

### ISSUE THREAD

**Issue by wunny83** [zeromq/clrzmq4#78]
Using Frames
while(true)
{
_socket.Send(new ZFrame(data));
_socket.Send(new ZFrame(data));
...x10
Thread.SpinWait(200);
}

vs

while(true)
{
_socket.SendBytes(data,0,data.Length);
_socket.SendBytes(data,0,data.Length);
...x10
Thread.SpinWait(200);
}

When stressing the socket to test max throughput causes memory to leak.
C# GC is bad at disposing objects created in one thread / then sent via zeromq but not disposed, instead left to be disposed by GC by going out of scope.

Changing the spinwait on the send to a thread.Sleep allows GC to collect that memory avoiding a memory leak,

while(true)
{
_socket.Send(new ZFrame(data));
_socket.Send(new ZFrame(data));
...x10
Thread.Sleep(100);
}

A fix may be in the C# lib to explicitly call _frame.Dispose() _message.Dispose() once the socket was done using the message.

**Comment by metadings** [comment]
Well, if you don't call ZFrame.Dispose, it's your own fault.

You can use SendBytes, to just send bytes; what you are doing with the bytes is on your own.

So you may have a `ZFrame frame`, where you can Write and Read on, you may also Send the data, however you MUST call Dispose.

There's a warning in the comment of ZFrame.SendBytes, you shouldn't use them. It's better you use Send/SendFrame instead of SendBytes. This mitigates what you've said, in that SendFrame does call Dispose, whereas SendBytes just sends some bytes.

**Comment by wunny83** [comment]
Forgot to mention

ZFrame.Dispose() is used

This does nothing... Try it out and see instead of closing the thread....

**Comment by wunny83** [comment]
Actually, after more testing, looks like Send(byte) / SendFrame(frame)
/Send(Frame) behave very similar in my code, it was actually my subscriber

But Sending Bytes is still most memory efficient rather than using frames.

foreach (ZFrame item in data)
{
        var stringDate=  item.ReadString(Encoding.UTF8);
        //Do Something () //Can do nothing
        item.Dispose();
}
data.Dispose();

Causing the memory leak...

This code was working previously using NUget ZeroMQ 3.0.0-rc1 and since
upgrading /porting to this Nuget ZeroMq4 package. we have been experiencing
issue with memory.

Since this is a throughput test, we are pushing it to limits.
We have solved this by using bytes for now...
