### ISSUE TITLE
Plugout network lead to server cannot receive packet

### ISSUE THREAD

**Issue by wenjians** [zeromq/clrzmq4#80]
Hi all,
I wrote a Windows (Win 10) service that using c#, which is based on dealer/route mode
- server works in router mode, which need to accept multiple clients working as dealer mode
- clients send notification to server and server don't response to clients

I write the code based on example : https://github.com/metadings/zguide/blob/master/examples/C%23/flserver3.cs, which works fine in normal case, even when the network was disconnected for short time, e.g. 30 seconds.

but after I plug out the network for 3 minutes and then plug in, then server could not receive any packet, but I saw the communication of TCP layer is still okay using Wireshark.

is anyone know such case and is there any good idea to solve this issue?

Best Regards,
Kevin

**Comment by metadings** [comment]
I don't know exactly... Disabling a network, disconnecting a network (WLAN) and plugging-out a network seems to make a difference. You should possibly ask this Q on zeromq/libzmq.

Please also tell exactly how you made your server and your clients.
For example, your Server should be a ROUTER/DEALER, where Server-Services are connecting using REP to the DEALER, and Clients are connecting using REQ to the ROUTER.
You should make sure your Server-Services are responding REP to the Client's REQ, because ZeroMQ does expect the response, if the Server-Services are not responding REP, the Client's REQ is just done again. This is the use-case for PUSH-PULL, where ZeroMQ doesn't expect a response.

**Comment by wenjians** [comment]
thanks a lot for your prompt answer.

The server is work as Router and the client work as dealer, according to the ZeroMQ guide (http://zguide.zeromq.org/page:all#The-Asynchronous-Client-Server-Pattern), this can be asynchronous mode, i.e. client can send one ore more request without waiting for response.  because the service is quite simple and network request is not so much, so we don't need multiple worker, so there is no works exist, only upper half exist, i.e. service receive the notification and just do it without any response.

**Comment by wenjians** [comment]
I submit a question in libzmq as well, so I will close here.
https://github.com/zeromq/libzmq/issues/2224
